// <auto-generated />
using System;
using API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(Ticket_DbContext))]
    partial class Ticket_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Domain.Ticket", b =>
                {
                    b.Property<int>("ticket_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticket_id"), 1L, 1);

                    b.Property<DateTime?>("assigned_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("resolution_note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("resolved_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ticket_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ticket_resolution_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ticket_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ticket_type")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ticket_id");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("API.Domain.Ticket_Note", b =>
                {
                    b.Property<int>("ticket_note_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticket_note_id"), 1L, 1);

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("fk_ticket_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_history_note")
                        .HasColumnType("bit");

                    b.Property<bool>("is_internal")
                        .HasColumnType("bit");

                    b.Property<string>("note_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ticket_id")
                        .HasColumnType("int");

                    b.HasKey("ticket_note_id");

                    b.HasIndex("ticket_id");

                    b.ToTable("TicketNote", (string)null);
                });

            modelBuilder.Entity("API.Domain.Ticket_Note", b =>
                {
                    b.HasOne("API.Domain.Ticket", "ticket")
                        .WithMany("ticket_notes")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("API.Domain.Ticket", b =>
                {
                    b.Navigation("ticket_notes");
                });
#pragma warning restore 612, 618
        }
    }
}
